In [1]:
import pandas as pd 
import seaborn as sns

In [2]:
df= sns.load_dataset('tips')

In [5]:
from sklearn.preprocessing import LabelEncoder
encoder_time=LabelEncoder()
encoded_data =encoder_time.fit_transform(df['time'])

In [6]:
print('classes',encoder_time.classes_)

classes ['Dinner' 'Lunch']

In [7]:
encoded_data

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [8]:
for category,number in zip (encoder_time.classes_, range(len(encoder_time.classes_))):
    print(category ,"----------", number)

Dinner ---------- 0
Lunch ---------- 1

In [17]:
encoder_day=LabelEncoder()
encoded_day_data =encoder_day.fit_transform(df['day'])

In [18]:
print('classes',encoder_day.classes_)

classes ['Fri' 'Sat' 'Sun' 'Thur']

In [20]:
for category,number in zip (encoder_day.classes_, range(len(encoder_day.classes_))):
    print(category ,"----------", number)

Fri ---------- 0
Sat ---------- 1
Sun ---------- 2
Thur ---------- 3

In [21]:
from sklearn.preprocessing import OneHotEncoder

In [22]:
encoder_day.inverse_transform([0,1,2,3])

array(['Fri', 'Sat', 'Sun', 'Thur'], dtype=object)

In [23]:
from sklearn.preprocessing import OneHotEncoder

In [24]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [25]:
ohe=OneHotEncoder(sparse_output=False)
ohe.fit_transform(df[['sex','smoker']])

array([[1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.]])

In [26]:
ohe=OneHotEncoder(sparse_output=False, drop='first')
ohe_encoder=ohe.fit_transform(df[['sex','smoker']])
ohe_encoder

array([[0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 1.],
       [0., 0.],
       [1., 1.],
       [1., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [0., 0.],
       [1., 1.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [0., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [1., 1.],
       [0., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [0., 0.],
       [1., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [1., 1.],
       [1., 1.],
       [0., 0.],
       [1., 0.],
       [0., 1.],
       [1., 1.],
       [1., 0.],
       [0., 0.]])

In [27]:
df1=pd.DataFrame(ohe_encoder,columns=ohe.get_feature_names_out())
df1

     sex_Male  smoker_Yes
0         0.0         0.0
1         1.0         0.0
2         1.0         0.0
3         1.0         0.0
4         0.0         0.0
..        ...         ...
239       1.0         0.0
240       0.0         1.0
241       1.0         1.0
242       1.0         0.0
243       0.0         0.0

[244 rows x 2 columns]

In [28]:
pd.concat([df,df1],axis=1)

     total_bill   tip     sex smoker   day    time  size  sex_Male  smoker_Yes
0         16.99  1.01  Female     No   Sun  Dinner     2       0.0         0.0
1         10.34  1.66    Male     No   Sun  Dinner     3       1.0         0.0
2         21.01  3.50    Male     No   Sun  Dinner     3       1.0         0.0
3         23.68  3.31    Male     No   Sun  Dinner     2       1.0         0.0
4         24.59  3.61  Female     No   Sun  Dinner     4       0.0         0.0
..          ...   ...     ...    ...   ...     ...   ...       ...         ...
239       29.03  5.92    Male     No   Sat  Dinner     3       1.0         0.0
240       27.18  2.00  Female    Yes   Sat  Dinner     2       0.0         1.0
241       22.67  2.00    Male    Yes   Sat  Dinner     2       1.0         1.0
242       17.82  1.75    Male     No   Sat  Dinner     2       1.0         0.0
243       18.78  3.00  Female     No  Thur  Dinner     2       0.0         0.0

[244 rows x 9 columns]

In [30]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np

In [33]:
log_2 =FunctionTransformer(np.log2)
log_2.fit_transform(df['tip'])

0      0.014355
1      0.731183
2      1.807355
3      1.726831
4      1.851999
         ...
239    2.565597
240    1.000000
241    1.000000
242    0.807355
243    1.584963
Name: tip, Length: 244, dtype: float64

In [34]:
import numpy as np

In [35]:
from sklearn.preprocessing import PowerTransformer

In [36]:
#A right-skewedvfeature
X = np.array([
[-1],
[0,],
[3],
[5],
[10],
[50]])
#create the tranformer
pt= PowerTransformer(method="yeo-johnson")

#Fit and transform
X_transformed = pt.fit_transform(X)

print("Original:")
print(X.ravel())
print("\nTranformed:")
print(np.round(X_transformed.ravel(), 3))
print("\nLearned lambda:")
print(pt.lambdas_)

Original:
[-1  0  3  5 10 50]

Tranformed:
[-1.54  -0.801 -0.045  0.195  0.571  1.619]

Learned lambda:
[0.09126797]

In [41]:
#A right-skewedvfeature
y = np.array([
[1],[3],[5],[10],[50]])
#create the tranformer
pt= PowerTransformer(method="box-cox")

#Fit and transform
y_transformed = pt.fit_transform(y)

print("Original:")
print(y.ravel())
print("\nTranformed:")
print(np.round(y_transformed.ravel(), 3))
print("\nLearned lambda:")
print(pt.lambdas_)

Original:
[ 1  3  5 10 50]

Tranformed:
[-1.487 -0.471 -0.049  0.479  1.528]

Learned lambda:
[-0.13754482]

In [43]:
import pandas as pd

# Load the generated CSV dataset
df = pd.read_csv("sample_dataset.csv")

# Display the first few rows
print(df)

# Check missing values count per column
print("\nMissing values per column:")
print(df.isnull().sum())

    ID    Name   Age  Gender Department   Salary  Experience_Years       City  \
0  101   Aarav  25.0    Male         IT  55000.0               2.0     Mumbai
1  102    Diya  31.0  Female         HR      NaN               5.0      Delhi
2  103   Rohan   NaN    Male         IT  72000.0               6.0  Bangalore
3  104   Pooja  28.0  Female        NaN  48000.0               3.0        NaN
4  105   Kabir  35.0    Male    Finance  85000.0               NaN     Mumbai
5  106    Neha   NaN  Female  Marketing  52000.0               4.0       Pune
6  107  Vikram  42.0    Male         HR  95000.0              12.0      Delhi
7  108  Ananya  24.0     NaN    Finance      NaN               1.0  Bangalore
8  109  Suresh  38.0    Male         IT  80000.0               9.0        NaN
9  110   Meera   NaN  Female        NaN  60000.0               NaN    Chennai

  Purchased
0       Yes
1        No
2       Yes
3        No
4       Yes
5       NaN
6       Yes
7        No
8       Yes
9        No

Missing values per column:
ID                  0
Name                0
Age                 3
Gender              1
Department          2
Salary              2
Experience_Years    2
City                2
Purchased           1
dtype: int64

In [42]:
from sklearn.impute import SimpleImputer

In [46]:
df= pd.DataFrame(df)

In [44]:
df.head()

,ID,Name,Age,Gender,Department,Salary,Experience_Years,City,Purchased
0,101,Aarav,25.0,Male,IT,55000.0,2.0,Mumbai,Yes
1,102,Diya,31.0,Female,HR,NaN,5.0,Delhi,No
2,103,Rohan,NaN,Male,IT,72000.0,6.0,Bangalore,Yes
3,104,Pooja,28.0,Female,NaN,48000.0,3.0,NaN,No
4,105,Kabir,35.0,Male,Finance,85000.0,NaN,Mumbai,Yes

In [47]:
imputer=  SimpleImputer(strategy='mean')
imputer.fit_transform(df[['Salary']])

array([[55000.],
       [68375.],
       [72000.],
       [48000.],
       [85000.],
       [52000.],
       [95000.],
       [68375.],
       [80000.],
       [60000.]])

In [48]:
imputer=SimpleImputer(strategy='mean')

In [50]:
df['new_salary']=imputer.fit_transform(df[['Salary']]).flatten()

In [51]:
df

,ID,Name,Age,Gender,Department,Salary,Experience_Years,City,Purchased,new_salary
0,101,Aarav,25.0,Male,IT,55000.0,2.0,Mumbai,Yes,55000.0
1,102,Diya,31.0,Female,HR,NaN,5.0,Delhi,No,68375.0
2,103,Rohan,NaN,Male,IT,72000.0,6.0,Bangalore,Yes,72000.0
3,104,Pooja,28.0,Female,NaN,48000.0,3.0,NaN,No,48000.0
4,105,Kabir,35.0,Male,Finance,85000.0,NaN,Mumbai,Yes,85000.0
5,106,Neha,NaN,Female,Marketing,52000.0,4.0,Pune,NaN,52000.0
6,107,Vikram,42.0,Male,HR,95000.0,12.0,Delhi,Yes,95000.0
7,108,Ananya,24.0,NaN,Finance,NaN,1.0,Bangalore,No,68375.0
8,109,Suresh,38.0,Male,IT,80000.0,9.0,NaN,Yes,80000.0
9,110,Meera,NaN,Female,NaN,60000.0,NaN,Chennai,No,60000.0

In [55]:
imputer=SimpleImputer(strategy='median')
df['new_Experience_years']=imputer.fit_transform(df[['new_salary']]).flatten()

In [56]:
df

,ID,Name,Age,Gender,Department,Salary,Experience_Years,City,Purchased,new_salary,Experience_years,new_Experience_years
0,101,Aarav,25.0,Male,IT,55000.0,2.0,Mumbai,Yes,55000.0,55000.0,55000.0
1,102,Diya,31.0,Female,HR,NaN,5.0,Delhi,No,68375.0,68375.0,68375.0
2,103,Rohan,NaN,Male,IT,72000.0,6.0,Bangalore,Yes,72000.0,72000.0,72000.0
3,104,Pooja,28.0,Female,NaN,48000.0,3.0,NaN,No,48000.0,48000.0,48000.0
4,105,Kabir,35.0,Male,Finance,85000.0,NaN,Mumbai,Yes,85000.0,85000.0,85000.0
5,106,Neha,NaN,Female,Marketing,52000.0,4.0,Pune,NaN,52000.0,52000.0,52000.0
6,107,Vikram,42.0,Male,HR,95000.0,12.0,Delhi,Yes,95000.0,95000.0,95000.0
7,108,Ananya,24.0,NaN,Finance,NaN,1.0,Bangalore,No,68375.0,68375.0,68375.0
8,109,Suresh,38.0,Male,IT,80000.0,9.0,NaN,Yes,80000.0,80000.0,80000.0
9,110,Meera,NaN,Female,NaN,60000.0,NaN,Chennai,No,60000.0,60000.0,60000.0

In [59]:
imputer=SimpleImputer(strategy='most_frequent',)
df['new_city']=imputer.fit_transform(df[['City']]).flatten()

In [60]:
df

,ID,Name,Age,Gender,Department,Salary,Experience_Years,City,Purchased,new_salary,Experience_years,new_Experience_years,city,new_city
0,101,Aarav,25.0,Male,IT,55000.0,2.0,Mumbai,Yes,55000.0,55000.0,55000.0,Mumbai,Mumbai
1,102,Diya,31.0,Female,HR,NaN,5.0,Delhi,No,68375.0,68375.0,68375.0,Delhi,Delhi
2,103,Rohan,NaN,Male,IT,72000.0,6.0,Bangalore,Yes,72000.0,72000.0,72000.0,Bangalore,Bangalore
3,104,Pooja,28.0,Female,NaN,48000.0,3.0,NaN,No,48000.0,48000.0,48000.0,Bangalore,Bangalore
4,105,Kabir,35.0,Male,Finance,85000.0,NaN,Mumbai,Yes,85000.0,85000.0,85000.0,Mumbai,Mumbai
5,106,Neha,NaN,Female,Marketing,52000.0,4.0,Pune,NaN,52000.0,52000.0,52000.0,Pune,Pune
6,107,Vikram,42.0,Male,HR,95000.0,12.0,Delhi,Yes,95000.0,95000.0,95000.0,Delhi,Delhi
7,108,Ananya,24.0,NaN,Finance,NaN,1.0,Bangalore,No,68375.0,68375.0,68375.0,Bangalore,Bangalore
8,109,Suresh,38.0,Male,IT,80000.0,9.0,NaN,Yes,80000.0,80000.0,80000.0,Bangalore,Bangalore
9,110,Meera,NaN,Female,NaN,60000.0,NaN,Chennai,No,60000.0,60000.0,60000.0,Chennai,Chennai

: